# Configuration for labeler - https://github.com/actions/labeler
dependencies:
- ./**/pom.xml
- pom.xml

chore:
- .github/**/*
- ./*.sh
- Makefile
- ./*.yml
- ./*.enc
- .gitignore
- Dockerfile*

documentation: 
- ./*.md
- ./**/*.md
- ./*.txt

tests:
- dockerfile-image-update-itest/**/*
- dockerfile-image-update/src/test/**/*
