name: 'Multi-Module Maven Build / Deploy'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'dockerfile-image-update-') == false
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: docker build
        run: make mvn-build get-main-project-target-dir
      - name: integration test
        env:
          ITEST_GH_TOKEN: ${{ secrets.ITEST_GH_TOKEN }}
        run: make integration-test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./dockerfile-image-update/target/site/jacoco/jacoco.xml
          # flags: unittests
          # yml: ./codecov.yml
          fail_ci_if_error: true
  master-deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: deploy
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
