name: 'Multi-Module Maven Build / Deploy'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pr-branch-test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master' && ! startsWith('dockerfile-image-update-', github.ref)
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: docker build
        run: docker build -t salesforce/dockerfile-image-update .
      - name: build integration test jar
        uses: docker://maven:3.6-jdk-11
        with:
          args: 'install -pl dockerfile-image-update-itest -am -DskipTests'
      - name: integration test
        env:
          ITEST_GH_TOKEN: ${{ secrets.ITEST_GH_TOKEN }}
        run: |
          echo git_api_token=${ITEST_GH_TOKEN} > `pwd`/itest.env
          export user_itest_secrets_file_secret=`pwd`/itest.env
          docker-compose up #--abort-on-container-exit TODO: remove this once itests can be made not to flap see issue #21
          rm itest.env
  master-test-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: docker build
        run: docker build -t salesforce/dockerfile-image-update .
      - name: build integration test jar
        uses: docker://maven:3.6-jdk-11
        with:
          args: 'install -pl dockerfile-image-update-itest -am -DskipTests'
      - name: integration test
        env:
          ITEST_GH_TOKEN: ${{ secrets.ITEST_GH_TOKEN }}
        run: |
          echo git_api_token=${ITEST_GH_TOKEN} > `pwd`/itest.env
          export user_itest_secrets_file_secret=`pwd`/itest.env
          docker-compose up #--abort-on-container-exit TODO: remove this once itests can be made not to flap see issue #21
          rm itest.env
